#!/bin/zsh

if [ $# -ne 1 ]; then
    echo "Invalid Usage.";
    echo "Usage: hb_stat [directory]";
    exit 1;
fi;

if  ! [ -d $1 ]; then
    echo "Error: $1 does not exist/is not a directory.";
    exit 1;
fi;

if ! [ -f $1/.reencode ]; then
   echo "Error: $1 does not contain the reencode file list, run 'find_all'";
   exit 1;
fi;

printf "Complete: ";
cat $1/.reencode | while read i; do if ! [ -f $1/$i ] && [ -f $1/$i.conv.mkv ]; then echo $i; fi; done | wc -l;

printf "Remaining: ";
cat $1/.reencode | while read i; do if [ -f $1/$i ] && ! [ -f $1/$i.conv.mkv ] ; then echo $i; fi; done | wc -l 
echo;

echo "Finished: ";
cat $1/.reencode | while read i; do if ! [ -f $1/$i ] && [ -f $1/$i.conv.mkv ]; then echo $i; fi; done | tail -n 5;
echo;

echo "Current: ";
cat $1/.reencode | while read i; do if [ -f $1/$i ] && [ -f $1/$i.conv.mkv ]; then echo $i; fi; done;
echo;

echo "Next: ";
cat $1/.reencode | while read i; do if [ -f $1/$i ] && ! [ -f $1/$i.conv.mkv ] ; then echo $i; fi; done | head -n 5;
