#!/bin/zsh

if [ $# -ne 1 ]; then
    echo "Invalid Usage.";
    echo "Usage: find_all [directory]";
    exit 1;
fi;

if  ! [ -d $1 ]; then
    echo "Error: $1 does not exist/is not a directory.";
    exit 1;
fi;

if ! [ -f $1/.reencode ]; then
   echo "Error: $1 does not contain the reencode file list, run 'find_all'";
   exit 1;
fi;

mkdir $1/delete;

cat $1/.reencode | while read i; do HandBrakeCLI -i $1/$i -o $1/$i.conv.mkv -e x265 -q 24.5 -a 1,2,3,4,5,6 -E copy:ac3 -B 160 -6 dpl2 -R Auto -D 0.0 --audio-copy-mask aac,ac3,dtshd,dts,mp3 --audio-fallback ffac3 -X 1280 -Y 720 -s "1,2,3,4,5,6" < /dev/null; mv -v $i delete ; done;
